import { Label } from '../interfaces/label.interface';

export const COLOR_PRIMARY= '#6E8684';

export const LABEL_VOID: Label = {
  color:'',
  icon: '',
  id: '',
};

export const allLabels: Label[] = [
  { id: '', color: COLOR_PRIMARY, icon: 'airplane' },
  { id: '', color: COLOR_PRIMARY, icon: 'apple' },
  { id: '', color: COLOR_PRIMARY, icon: 'bag' },
  { id: '', color: COLOR_PRIMARY, icon: 'balloon' },
  { id: '', color: COLOR_PRIMARY, icon: 'band' },
  { id: '', color: COLOR_PRIMARY, icon: 'bed' },
  { id: '', color: COLOR_PRIMARY, icon: 'beer' },
  { id: '', color: COLOR_PRIMARY, icon: 'bicycle' },
  { id: '', color: COLOR_PRIMARY, icon: 'bill' },
  { id: '', color: COLOR_PRIMARY, icon: 'book' },
  { id: '', color: COLOR_PRIMARY, icon: 'bus' },
  { id: '', color: COLOR_PRIMARY, icon: 'cafe' },
  { id: '', color: COLOR_PRIMARY, icon: 'camera' },
  { id: '', color: COLOR_PRIMARY, icon: 'car' },
  { id: '', color: COLOR_PRIMARY, icon: 'card' },
  { id: '', color: COLOR_PRIMARY, icon: 'cart' },
  { id: '', color: COLOR_PRIMARY, icon: 'cash' },
  { id: '', color: COLOR_PRIMARY, icon: 'control' },
  { id: '', color: COLOR_PRIMARY, icon: 'cripto' },
  { id: '', color: COLOR_PRIMARY, icon: 'cut' },
  { id: '', color: COLOR_PRIMARY, icon: 'desktop' },
  { id: '', color: COLOR_PRIMARY, icon: 'earth' },
  { id: '', color: COLOR_PRIMARY, icon: 'fast-food' },
  { id: '', color: COLOR_PRIMARY, icon: 'ferry' },
  { id: '', color: COLOR_PRIMARY, icon: 'film' },
  { id: '', color: COLOR_PRIMARY, icon: 'fish' },
  { id: '', color: COLOR_PRIMARY, icon: 'football' },
  { id: '', color: COLOR_PRIMARY, icon: 'gift' },
  { id: '', color: COLOR_PRIMARY, icon: 'glasses' },
  { id: '', color: COLOR_PRIMARY, icon: 'gym' },
  { id: '', color: COLOR_PRIMARY, icon: 'happy' },
  { id: '', color: COLOR_PRIMARY, icon: 'heart' },
  { id: '', color: COLOR_PRIMARY, icon: 'home' },
  { id: '', color: COLOR_PRIMARY, icon: 'ice-cream' },
  { id: '', color: COLOR_PRIMARY, icon: 'id-card' },
  { id: '', color: COLOR_PRIMARY, icon: 'label' },
  { id: '', color: COLOR_PRIMARY, icon: 'laptop' },
  { id: '', color: COLOR_PRIMARY, icon: 'library' },
  { id: '', color: COLOR_PRIMARY, icon: 'male' },
  { id: '', color: COLOR_PRIMARY, icon: 'music' },
  { id: '', color: COLOR_PRIMARY, icon: 'paw' },
  { id: '', color: COLOR_PRIMARY, icon: 'people' },
  { id: '', color: COLOR_PRIMARY, icon: 'pizza' },
  { id: '', color: COLOR_PRIMARY, icon: 'puzzle' },
  { id: '', color: COLOR_PRIMARY, icon: 'repeat' },
  { id: '', color: COLOR_PRIMARY, icon: 'restaurant' },
  { id: '', color: COLOR_PRIMARY, icon: 'school' },
  { id: '', color: COLOR_PRIMARY, icon: 'shapes' },
  { id: '', color: COLOR_PRIMARY, icon: 'shirt' },
  { id: '', color: COLOR_PRIMARY, icon: 'store' },
  { id: '', color: COLOR_PRIMARY, icon: 'subway' },
  { id: '', color: COLOR_PRIMARY, icon: 'ticket' },
  { id: '', color: COLOR_PRIMARY, icon: 'tool' },
  { id: '', color: COLOR_PRIMARY, icon: 'train' },
  { id: '', color: COLOR_PRIMARY, icon: 'trash' },
  { id: '', color: COLOR_PRIMARY, icon: 'videocam' },
  { id: '', color: COLOR_PRIMARY, icon: 'wallet' },
  { id: '', color: COLOR_PRIMARY, icon: 'watch' },
  { id: '', color: COLOR_PRIMARY, icon: 'water' },
  { id: '', color: COLOR_PRIMARY, icon: 'wine' },
];
