import { Label } from '../interfaces/label.interface';

export const COLOR_PRIMARY= '#6E8684';

export const LABEL_VOID: Label = {
  color:'',
  name: '',
  id: 1,
};

export const allLabels: Label[] = [
  { id: 0, color: COLOR_PRIMARY, name: 'airplane' },
  { id: 0, color: COLOR_PRIMARY, name: 'apple' },
  { id: 0, color: COLOR_PRIMARY, name: 'bag' },
  { id: 0, color: COLOR_PRIMARY, name: 'balloon' },
  { id: 0, color: COLOR_PRIMARY, name: 'band' },
  { id: 0, color: COLOR_PRIMARY, name: 'bed' },
  { id: 0, color: COLOR_PRIMARY, name: 'beer' },
  { id: 0, color: COLOR_PRIMARY, name: 'bicycle' },
  { id: 0, color: COLOR_PRIMARY, name: 'bill' },
  { id: 0, color: COLOR_PRIMARY, name: 'book' },
  { id: 0, color: COLOR_PRIMARY, name: 'bus' },
  { id: 0, color: COLOR_PRIMARY, name: 'cafe' },
  { id: 0, color: COLOR_PRIMARY, name: 'camera' },
  { id: 0, color: COLOR_PRIMARY, name: 'car' },
  { id: 0, color: COLOR_PRIMARY, name: 'card' },
  { id: 0, color: COLOR_PRIMARY, name: 'cart' },
  { id: 0, color: COLOR_PRIMARY, name: 'cash' },
  { id: 0, color: COLOR_PRIMARY, name: 'control' },
  { id: 0, color: COLOR_PRIMARY, name: 'cripto' },
  { id: 0, color: COLOR_PRIMARY, name: 'cut' },
  { id: 0, color: COLOR_PRIMARY, name: 'desktop' },
  { id: 0, color: COLOR_PRIMARY, name: 'earth' },
  { id: 0, color: COLOR_PRIMARY, name: 'fast-food' },
  { id: 0, color: COLOR_PRIMARY, name: 'ferry' },
  { id: 0, color: COLOR_PRIMARY, name: 'film' },
  { id: 0, color: COLOR_PRIMARY, name: 'fish' },
  { id: 0, color: COLOR_PRIMARY, name: 'football' },
  { id: 0, color: COLOR_PRIMARY, name: 'gift' },
  { id: 0, color: COLOR_PRIMARY, name: 'glasses' },
  { id: 0, color: COLOR_PRIMARY, name: 'gym' },
  { id: 0, color: COLOR_PRIMARY, name: 'happy' },
  { id: 0, color: COLOR_PRIMARY, name: 'heart' },
  { id: 0, color: COLOR_PRIMARY, name: 'home' },
  { id: 0, color: COLOR_PRIMARY, name: 'ice-cream' },
  { id: 0, color: COLOR_PRIMARY, name: 'id-card' },
  { id: 0, color: COLOR_PRIMARY, name: 'label' },
  { id: 0, color: COLOR_PRIMARY, name: 'laptop' },
  { id: 0, color: COLOR_PRIMARY, name: 'library' },
  { id: 0, color: COLOR_PRIMARY, name: 'male' },
  { id: 0, color: COLOR_PRIMARY, name: 'music' },
  { id: 0, color: COLOR_PRIMARY, name: 'paw' },
  { id: 0, color: COLOR_PRIMARY, name: 'people' },
  { id: 0, color: COLOR_PRIMARY, name: 'pizza' },
  { id: 0, color: COLOR_PRIMARY, name: 'puzzle' },
  { id: 0, color: COLOR_PRIMARY, name: 'repeat' },
  { id: 0, color: COLOR_PRIMARY, name: 'restaurant' },
  { id: 0, color: COLOR_PRIMARY, name: 'school' },
  { id: 0, color: COLOR_PRIMARY, name: 'shapes' },
  { id: 0, color: COLOR_PRIMARY, name: 'shirt' },
  { id: 0, color: COLOR_PRIMARY, name: 'store' },
  { id: 0, color: COLOR_PRIMARY, name: 'subway' },
  { id: 0, color: COLOR_PRIMARY, name: 'ticket' },
  { id: 0, color: COLOR_PRIMARY, name: 'tool' },
  { id: 0, color: COLOR_PRIMARY, name: 'train' },
  { id: 0, color: COLOR_PRIMARY, name: 'trash' },
  { id: 0, color: COLOR_PRIMARY, name: 'videocam' },
  { id: 0, color: COLOR_PRIMARY, name: 'wallet' },
  { id: 0, color: COLOR_PRIMARY, name: 'watch' },
  { id: 0, color: COLOR_PRIMARY, name: 'water' },
  { id: 0, color: COLOR_PRIMARY, name: 'wine' },
];
